### ISSUE TITLE
v2.0 App Store release

### ISSUE THREAD

**Issue by alechemy** [ericbomgardner/tabless#8]
Congrats on releasing v2.0 of your app! 🎉 It looks like it contains some cool improvements.

Is there a plan to publish it to the App Store?

**Comment by ericbomgardner** [comment]
Hey @alechemy, oops I jumped the gun a bit with creating the release heh 😅 

I usually use a TestFlight version of any potential release build on my phone for a while to verify it's working before deploying to the App Store, and I've hit some issues with this build that I'll want to address before deploying, notably:
- Content blocking blocks legitimate parts of the web -- this could probably be fixed by improving the configurability of blocklists used, but I'll probably just leave content blocking disabled by default to be able to ship the change without breaking things for people by default
- I've noticed a weird issue when navigating back and forward in the last couple of weeks; I don't want to ship until figuring out what's up with that

(And since this is a hobby project for me, I only occasionally work on it in my downtime, so it could be a while before I ship anything unfortunately...)

But thanks for your interest! If you'd like to try out the [2-0.6](https://github.com/ericbomgardner/tabless/releases/tag/2.0-6) build in the meantime, feel free to join this TestFlight group: https://testflight.apple.com/join/9KwuCFVg -- Apple still needs to approve the build but it should be pretty quick! 🙏🏻

**Comment by alechemy** [comment]
Thanks for that info, @ericbomgardner ! Makes total sense. 

I would totally be down to take the beta for a spin. Though, I tried to access the provided TestFlight link, but was met with a "This beta isn't accepting any new testers right now" message.

**Comment by ericbomgardner** [comment]
Hm, I got that message too before the build was approved for TestFlight distribution, but it was approved an hour after your message -- does trying the link again work for you now?

**Comment by alechemy** [comment]
Works now! Cheers

**Comment by ericbomgardner** [comment]
2.0 (https://github.com/ericbomgardner/tabless/releases/tag/2.0-7) has now been published to the App Store
